title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
gem "github-pages", group: :jekyll_plugins
title: [HO TONG MINH Dinh]
description: [About me and my jobs]
